common:
  application-name: zero-schedule-development
  swagger:
    enable: true
  sequence:
    workerId: 1
    datacenterId: 1
  mysql:
    ip: 10.20.9.104
    port: 3306
    username: root
    password: 123456